global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway']

  - job_name: 'localhost'
    static_configs:
      - targets: ['host.docker.internal:5283']

  - job_name: 'telemetryTest'
    static_configs:
      - targets: ['host.docker.internal:5217']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:15692']
